# Generated by Django 4.2.6 on 2023-12-23 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('product_id', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('product_name', models.CharField(max_length=255)),
                ('description_of_product', models.CharField(max_length=255)),
                ('picture_in_browsing', models.ImageField(blank=True, null=True, upload_to='product_images/')),
                ('picture_in_description', models.ImageField(blank=True, null=True, upload_to='product_images/')),
                ('price', models.IntegerField()),
                ('quantity_in_stock', models.IntegerField()),
            ],
            options={
                'db_table': 'product',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('user_id', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('account', models.CharField(max_length=255, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255)),
                ('phone_number', models.CharField(max_length=255)),
                ('permission', models.IntegerField()),
                ('status', models.IntegerField()),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
